name: Lint

on:
  pull_request:

jobs:
  golangci:
    name: golangci‑lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      # optional: install the very latest golangci-lint binary
      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          echo "::add-path::${{ env.GOPATH }}/bin"

      - name: Run golangci-lint via Action
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --enable bodyclose --timeout 10m
          only-new-issues: true
